
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftMULDIVleftPOWrightUMINUSDIV LPAREN MINUS MUL NUM PLUS POW RPARENexpr : expr PLUS expr\n| expr MINUS expr\n| expr MUL expr\n| expr DIV expr\n| expr POW exprexpr : MINUS expr %prec UMINUSexpr : LPAREN expr RPARENexpr : NUM'
    
_lr_action_items = {'MINUS':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,],[2,6,2,2,-8,2,2,2,2,2,-6,6,-1,-2,-3,-4,-5,-7,]),'LPAREN':([0,2,3,5,6,7,8,9,],[3,3,3,3,3,3,3,3,]),'NUM':([0,2,3,5,6,7,8,9,],[4,4,4,4,4,4,4,4,]),'$end':([1,4,10,12,13,14,15,16,17,],[0,-8,-6,-1,-2,-3,-4,-5,-7,]),'PLUS':([1,4,10,11,12,13,14,15,16,17,],[5,-8,-6,5,-1,-2,-3,-4,-5,-7,]),'MUL':([1,4,10,11,12,13,14,15,16,17,],[7,-8,-6,7,7,7,-3,-4,-5,-7,]),'DIV':([1,4,10,11,12,13,14,15,16,17,],[8,-8,-6,8,8,8,-3,-4,-5,-7,]),'POW':([1,4,10,11,12,13,14,15,16,17,],[9,-8,-6,9,9,9,9,9,-5,-7,]),'RPAREN':([4,10,11,12,13,14,15,16,17,],[-8,-6,17,-1,-2,-3,-4,-5,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,2,3,5,6,7,8,9,],[1,10,11,12,13,14,15,16,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> expr PLUS expr','expr',3,'p_expr_binop','zadanie2.py',140),
  ('expr -> expr MINUS expr','expr',3,'p_expr_binop','zadanie2.py',141),
  ('expr -> expr MUL expr','expr',3,'p_expr_binop','zadanie2.py',142),
  ('expr -> expr DIV expr','expr',3,'p_expr_binop','zadanie2.py',143),
  ('expr -> expr POW expr','expr',3,'p_expr_binop','zadanie2.py',144),
  ('expr -> MINUS expr','expr',2,'p_expr_uminus','zadanie2.py',166),
  ('expr -> LPAREN expr RPAREN','expr',3,'p_expr_group','zadanie2.py',171),
  ('expr -> NUM','expr',1,'p_expr_number','zadanie2.py',175),
]
